### ISSUE TITLE
Dependency curl

### ISSUE THREAD

**Issue by hksapiens** [jschmid1/gopro_as_webcam_on_linux#1]
Really nice job, works almost out of the box for me (tested with GoPro 9 Black).
Obviously curl is a dependency. That's why it failed for me after the first try :+1:

**Comment by jschmid1** [comment]
Thanks for reporting @hksapiens ! I'll make sure to add it as a dependency

**Comment by jschmid1** [comment]
resolved with https://github.com/jschmid1/gopro_as_webcam_on_linux/pull/3
