### ISSUE TITLE
hero 7 black instruction

### ISSUE THREAD

**Issue by irowbin** [jschmid1/gopro_as_webcam_on_linux#12]
I have a hero 7 black and had an issue while firing up this cmd `sudo gopro webcam` it says  `v4l2loopback could not be unloaded. There is maybe an ffmpeg(or similar) running that uses this module`.

I indeed installed this `v4l2loopback` and used for `droidcam` to use my android device as a webcam but I also want to use my gopro as a webcam too.  

Thanks.

**Comment by gothma** [comment]
This does not work for GoPros below Hero 8. GoPro 4-7 need a HDMI adapters and some kind of capture card.

Source: https://gopro.com/en/us/news/how-to-use-gopro-for-webcam

**Comment by NewoIsTaken** [comment]
Hi @irowbin, unfortunately, the HERO7 will not be supported because it does not have the GoPro Connect/webcam mode feature.
