### ISSUE TITLE
Can't seem to get past the install, really not positive what my issue is?

### ISSUE THREAD

**Issue by tinker-dot-bin** [jschmid1/gopro_as_webcam_on_linux#16]
Running the new script

`/dev/fd/63:` line 20: curl: command not found
chmod: cannot access '/usr/local/sbin/gopro': No such file or directory
**********************

The GoPro install script succeeded
Run with with: 
sudo gopro

**********************
sudo: gopro: command not found`

running the deprecated script

`Leaving this here to maintain backwards compatibility to any users who may just do a backwards search in their history to re-run this script.

Just FYI, there is a new version of the script with more functionality, including:

* Provide a device pattern for which look for
* Provide a device directly
* Provide an IP
* Auto-start and Preview mode.
* and more..

All of these features will hopefully simplify using a GoPro as a camera in the day-to-day life by allowing it to run automated in a start-up script.

If you wish to use the new version just check the Github repository. The README should be updated.
v4l2loopback is not loaded!
v4l2loopback was successfully loaded.
Please plug in your GoPro and switch it on. If it booted successfully (Charger icon on screen), hit Return

I can only make an uneducated guess wrt the name of the interface that the GoPro exposes.
For me the name of the interface is 'enxf64854ee7472'. This script will try to discover the device
that was added *last*, as you just plugged in the camera, hence the interface added last should be the one we're looking for.

Discovered: enx36749da17635.
Using this to discover the IP.
Found 172.26.167.53
To control the GoPro, we need to contact another interface (IP ending with .51).. Adapting internally..
Now using this IP internally: 172.26.167.51
/dev/fd/63: line 133: curl: command not found
Error while starting the Webcam mode. # TODO Useful message.`

Really excited to potentially resolve this :)

**Comment by NewoIsTaken** [comment]
@tinker-dot-bin, please install the `curl` package from your distribution's repositories!
Ubuntu/Debian: `sudo apt install curl`
Arch/Manjaro: `sudo pacman -Syu curl`
etc.
