### ISSUE TITLE
Error while starting the Webcam mode

### ISSUE THREAD

**Issue by helman** [jschmid1/gopro_as_webcam_on_linux#9]
I'm having an issue with the webcam mode. Not sure where is the error detail.

Device:
GoPro Hero 5 Session
Ubuntu 18.4.2 on Arm64
Wifi is connected to GoPro AP

```
$ sudo gopro webcam
Running GoPro Webcam Util for Linux [0.0.2]

       Launch Options
==========================
 * Non-interactive:  0
 * Autostart:        0
 * Preview:          0
==========================

v4l2loopback is loaded!
v4l2loopback was unloaded successfully.
v4l2loopback was successfully loaded.
Please plug in your GoPro and switch it on. If it booted successfully (Charger icon on screen), hit Return


Guessing the GoPro's device name...
I can only make an uneducated guess wrt the name of the interface that the GoPro exposes.
For me the name of the interface is 'enxf64854ee7472'. This script will try to discover the device
that was added *last*, as you just plugged in the camera, hence the interface added last should be the one we're looking for.

Discovered: wlx00e0232059ea.
Using wlx00e0232059ea to discover the GOPRO_IP.
Found 10.5.5.100
To control the GoPro, we need to contact another interface (GOPRO_IP ending with .51).. Adapting internally..
Now using this GOPRO_IP internally: 10.5.5.51
Error while starting the Webcam mode. # TODO Useful message.
```

Help would be much appreciated

**Comment by jschmid1** [comment]
I'd assume that the `wlx` device isn't the gopro and the script fails to detect it.

Try to disconnect the cable, wait a few seconds and then reconnect it. The script is faily dumb and uses the latest device that was added when no parameters are provided.

Alternatively try to figure out what the device is called for you (for me it starts with `enx`) and provide it with the `-p` flag

**Comment by helman** [comment]
Hi @jschmid1 
The 'wlx00e0232059ea' is my wireless interface, normally it's called 'wlan0' but mine is that one.
The script is able to detect my gropro 5 session IP address but i'm not sure what is happening, it just won't work. Do you know how to debug it or print out the error log?

**Comment by jschmid1** [comment]
> Hi @jschmid1
> The 'wlx00e0232059ea' is my wireless interface, normally it's called 'wlan0' but mine is that one.
> The script is able to detect my gropro 5 session IP address but i'm not sure what is happening, it just won't work. Do you know how to debug it or print out the error log?

try this

> Try to disconnect the cable, wait a few seconds and then reconnect it. The script is faily dumb and uses the latest device that was added when no parameters are provided.
> Alternatively try to figure out what the device is called for you (for me it starts with enx) and provide it with the -p flag

additionally there is a `-v` flag that enables verbose output.

**Comment by mehditlili** [comment]
There is just no gopro device in the network interface. I have a HERO 8 on Ubuntu 18.04 and when plugging the gopro I do not see any new device appearing when I run ifconfig or ip a.
Is there anything one needs to setup in order for the gopro to be detected as a network device?

**Comment by mehditlili** [comment]
Nevermind, had to disable MTP mode from the gopro settings and use GoPro connect instead.

**Comment by qq7te** [comment]
Hi @mehditlili , I think I'm in your same situation... I can't find any settings to disable MTP mode and use GoPro connect instead. I'm using HERO 8 Black on  ubuntu 20.04 
Maybe I need to update the firmware? I am on "camera version" 01.60

thanks, any help would be much appreciated

**Comment by mehditlili** [comment]
> Hi @mehditlili , I think I'm in your same situation... I can't find any settings to disable MTP mode and use GoPro connect instead. I'm using HERO 8 Black on ubuntu 20.04
> Maybe I need to update the firmware? I am on "camera version" 01.60
> 
> thanks, any help would be much appreciated

In preferences -> connections -> USB Connection
if you don't have it then probably firmware not up to date. I have a hero 8 black as well.

**Comment by qq7te** [comment]
Thanks, I've updated the firmware and now it works! 
Super laggy... but it works :)

**Comment by Fj00** [comment]
Any chance of this working for GoPro Hero+?

**Comment by jschmid1** [comment]
I don't have one unfortunately. Feel free to give it a try and report back here.

**Comment by NewoIsTaken** [comment]
> Any chance of this working for GoPro Hero+?

Most likely not. The only devices that have the GoPro Connect/webcam mode feature are the Hero 8 and 9.

**Comment by NewoIsTaken** [comment]
Hi @helman , unfortunately, the HERO5 is not supported because it does not have the GoPro Connect/webcam mode feature.
